{% set data= load_setup_py_data() %}
package:
  name: "ts-dateloc"
  version: {{ data.get('version') }}

source:
  path: ../

build:
  noarch: python  
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed .

test:
  requires:
    - ts-conda-build =0.3
    - palpy
    - rubin-scheduler
  source_files:
    - python
    - tests
    - setup.cfg
    - pyproject.toml
  commands:
    - pytest

requirements:
  host:
    - python {{ python }}
    - pip
    - setuptools_scm
    - setuptools
    - pytest-runner
  run:
    - python {{ python }}
    - setuptools
    - setuptools_scm
    - palpy
    - rubin-scheduler
